{
  "Header": {
    "Original": "CVE-2024-8418 (A flaw was found in Aardvark-dns versions 1.12.0 and 1.12.1. They cont ...)",
    "ID": "CVE-2024-8418",
    "Description": "(A flaw was found in Aardvark-dns versions 1.12.0 and 1.12.1. They cont ...)"
  },
  "Annotations": [
    {
      "Original": "- aardvark-dns 1.12.2-1 (bug #1080964)",
      "Type": "package",
      "Package": "aardvark-dns",
      "Kind": "fixed",
      "Version": "1.12.2-1",
      "BugNo": 1080964
    },
    {
      "Original": "NOTE: https://github.com/containers/aardvark-dns/issues/500",
      "Type": "NOTE",
      "Description": "https://github.com/containers/aardvark-dns/issues/500"
    },
    {
      "Original": "NOTE: https://github.com/containers/aardvark-dns/pull/503",
      "Type": "NOTE",
      "Description": "https://github.com/containers/aardvark-dns/pull/503"
    },
    {
      "Original": "NOTE: https://github.com/containers/aardvark-dns/commit/6d76c50978755b8162d176ec7eea0e09f8d57a42",
      "Type": "NOTE",
      "Description": "https://github.com/containers/aardvark-dns/commit/6d76c50978755b8162d176ec7eea0e09f8d57a42"
    },
    {
      "Original": "NOTE: https://github.com/containers/aardvark-dns/commit/39d0043c306c936fb5b6480b456cc1fdec869e25",
      "Type": "NOTE",
      "Description": "https://github.com/containers/aardvark-dns/commit/39d0043c306c936fb5b6480b456cc1fdec869e25"
    }
  ]
}