{
  "Header": {
    "Original": "CVE-2024-42005",
    "ID": "CVE-2024-42005"
  },
  "Annotations": [
    {
      "Original": "- python-django \u003cunfixed\u003e (bug #1078074)",
      "Type": "package",
      "Package": "python-django",
      "Kind": "unfixed",
      "BugNo": 1078074
    },
    {
      "Original": "NOTE: https://www.djangoproject.com/weblog/2024/aug/06/security-releases/",
      "Type": "NOTE",
      "Description": "https://www.djangoproject.com/weblog/2024/aug/06/security-releases/"
    },
    {
      "Original": "NOTE: https://github.com/django/django/commit/f4af67b9b41e0f4c117a8741da3abbd1c869ab28/ (4.2.15)",
      "Type": "NOTE",
      "Description": "https://github.com/django/django/commit/f4af67b9b41e0f4c117a8741da3abbd1c869ab28/ (4.2.15)"
    }
  ]
}