{
  "Header": {
    "Original": "CVE-2024-8947 (A vulnerability was found in MicroPython 1.22.2. It has been declared  ...)",
    "ID": "CVE-2024-8947",
    "Description": "(A vulnerability was found in MicroPython 1.22.2. It has been declared  ...)"
  },
  "Annotations": [
    {
      "Original": "- micropython \u003cunfixed\u003e",
      "Type": "package",
      "Package": "micropython",
      "Kind": "unfixed"
    },
    {
      "Original": "NOTE: https://github.com/micropython/micropython/issues/13283",
      "Type": "NOTE",
      "Description": "https://github.com/micropython/micropython/issues/13283"
    },
    {
      "Original": "NOTE: https://github.com/micropython/micropython/issues/13283#issuecomment-1918479709",
      "Type": "NOTE",
      "Description": "https://github.com/micropython/micropython/issues/13283#issuecomment-1918479709"
    },
    {
      "Original": "NOTE: Fixed by: https://github.com/micropython/micropython/commit/4bed614e707c0644c06e117f848fa12605c711cd (v1.23.0)",
      "Type": "NOTE",
      "Description": "Fixed by: https://github.com/micropython/micropython/commit/4bed614e707c0644c06e117f848fa12605c711cd (v1.23.0)"
    }
  ]
}