{
  "Header": {
    "Original": "CVE-2024-53907 [Potential denial-of-service in django.utils.html.strip_tags()]",
    "ID": "CVE-2024-53907",
    "Description": "[Potential denial-of-service in django.utils.html.strip_tags()]"
  },
  "Annotations": [
    {
      "Original": "- python-django 3:4.2.17-1",
      "Type": "package",
      "Package": "python-django",
      "Kind": "fixed",
      "Version": "3:4.2.17-1"
    },
    {
      "Original": "NOTE: https://www.djangoproject.com/weblog/2024/dec/04/security-releases/",
      "Type": "NOTE",
      "Description": "https://www.djangoproject.com/weblog/2024/dec/04/security-releases/"
    },
    {
      "Original": "NOTE: Fixed by: https://github.com/django/django/commit/790eb058b0716c536a2f2e8d1c6d5079d776c22b (4.2.17)",
      "Type": "NOTE",
      "Description": "Fixed by: https://github.com/django/django/commit/790eb058b0716c536a2f2e8d1c6d5079d776c22b (4.2.17)"
    }
  ]
}