{
  "Header": {
    "Original": "CVE-2024-8946 (A vulnerability was found in MicroPython 1.23.0. It has been classifie ...)",
    "ID": "CVE-2024-8946",
    "Description": "(A vulnerability was found in MicroPython 1.23.0. It has been classifie ...)"
  },
  "Annotations": [
    {
      "Original": "- micropython \u003cunfixed\u003e (bug #1082511)",
      "Type": "package",
      "Package": "micropython",
      "Kind": "unfixed",
      "BugNo": 1082511
    },
    {
      "Original": "NOTE: https://github.com/micropython/micropython/issues/13006",
      "Type": "NOTE",
      "Description": "https://github.com/micropython/micropython/issues/13006"
    },
    {
      "Original": "NOTE: https://github.com/micropython/micropython/issues/13006#issuecomment-1820309455",
      "Type": "NOTE",
      "Description": "https://github.com/micropython/micropython/issues/13006#issuecomment-1820309455"
    },
    {
      "Original": "NOTE: Fixed by: https://github.com/micropython/micropython/commit/29943546343c92334e8518695a11fc0e2ceea68b",
      "Type": "NOTE",
      "Description": "Fixed by: https://github.com/micropython/micropython/commit/29943546343c92334e8518695a11fc0e2ceea68b"
    }
  ]
}