{
  "Header": {
    "Original": "CVE-2022-48566 (An issue was discovered in compare_digest in Lib/hmac.py in Python thr ...)",
    "ID": "CVE-2022-48566",
    "Description": "(An issue was discovered in compare_digest in Lib/hmac.py in Python thr ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-3614-1 DLA-3575-1}",
      "Type": "xref",
      "Bugs": [
        "DLA-3614-1",
        "DLA-3575-1"
      ]
    },
    {
      "Original": "- python3.9 3.9.1~rc1-1",
      "Type": "package",
      "Package": "python3.9",
      "Kind": "fixed",
      "Version": "3.9.1~rc1-1"
    },
    {
      "Original": "- python3.7 \u003cremoved\u003e",
      "Type": "package",
      "Package": "python3.7",
      "Kind": "removed"
    },
    {
      "Original": "- python2.7 \u003cremoved\u003e",
      "Type": "package",
      "Package": "python2.7",
      "Kind": "removed"
    },
    {
      "Original": "[bullseye] - python2.7 2.7.18-8+deb11u1",
      "Type": "package",
      "Release": "bullseye",
      "Package": "python2.7",
      "Kind": "fixed",
      "Version": "2.7.18-8+deb11u1"
    },
    {
      "Original": "- pypy3 7.3.5+dfsg-2",
      "Type": "package",
      "Package": "pypy3",
      "Kind": "fixed",
      "Version": "7.3.5+dfsg-2"
    },
    {
      "Original": "NOTE: https://bugs.python.org/issue40791",
      "Type": "NOTE",
      "Description": "https://bugs.python.org/issue40791"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/commit/8183e11d87388e4e44e3242c42085b87a878f781 (v3.9.0b2)",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/commit/8183e11d87388e4e44e3242c42085b87a878f781 (v3.9.0b2)"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/commit/c1bbca5b004b3f74d240ef8a76ff445cc1a27efb (v3.9.1rc1)",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/commit/c1bbca5b004b3f74d240ef8a76ff445cc1a27efb (v3.9.1rc1)"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/commit/db95802bdfac4d13db3e2a391ec7b9e2f8d92dbe (v3.7.10)",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/commit/db95802bdfac4d13db3e2a391ec7b9e2f8d92dbe (v3.7.10)"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/commit/8bef9ebb1b88cfa4b2a38b93fe4ea22015d8254a (v3.6.13)",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/commit/8bef9ebb1b88cfa4b2a38b93fe4ea22015d8254a (v3.6.13)"
    },
    {
      "Original": "NOTE: https://github.com/pypy/pypy/commit/5a6b88b9e00053538a4cba1a9b4b92fbe619a33a (release-pypy3.7-v7.3.4rc1)",
      "Type": "NOTE",
      "Description": "https://github.com/pypy/pypy/commit/5a6b88b9e00053538a4cba1a9b4b92fbe619a33a (release-pypy3.7-v7.3.4rc1)"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/issues/84968",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/issues/84968"
    }
  ]
}