{
  "Header": {
    "Original": "CVE-2025-32914 (A flaw was found in libsoup, where the soup_multipart_new_from_message ...)",
    "ID": "CVE-2025-32914",
    "Description": "(A flaw was found in libsoup, where the soup_multipart_new_from_message ...)"
  },
  "Annotations": [
    {
      "Original": "- libsoup3 \u003cunfixed\u003e (bug #1103267)",
      "Type": "package",
      "Package": "libsoup3",
      "Kind": "unfixed",
      "BugNo": 1103267
    },
    {
      "Original": "- libsoup2.4 \u003cunfixed\u003e",
      "Type": "package",
      "Package": "libsoup2.4",
      "Kind": "unfixed"
    },
    {
      "Original": "NOTE: https://gitlab.gnome.org/GNOME/libsoup/-/issues/436",
      "Type": "NOTE",
      "Description": "https://gitlab.gnome.org/GNOME/libsoup/-/issues/436"
    }
  ]
}