{
  "Header": {
    "Original": "CVE-2025-32049 (A flaw was found in libsoup. The SoupWebsocketConnection may accept a  ...)",
    "ID": "CVE-2025-32049",
    "Description": "(A flaw was found in libsoup. The SoupWebsocketConnection may accept a  ...)"
  },
  "Annotations": [
    {
      "Original": "- libsoup3 \u003cunfixed\u003e",
      "Type": "package",
      "Package": "libsoup3",
      "Kind": "unfixed"
    },
    {
      "Original": "- libsoup2.4 \u003cunfixed\u003e",
      "Type": "package",
      "Package": "libsoup2.4",
      "Kind": "unfixed"
    },
    {
      "Original": "NOTE: https://gitlab.gnome.org/GNOME/libsoup/-/issues/390",
      "Type": "NOTE",
      "Description": "https://gitlab.gnome.org/GNOME/libsoup/-/issues/390"
    },
    {
      "Original": "NOTE: Fixed by: https://gitlab.gnome.org/GNOME/libsoup/-/commit/5a83501544a7ff180a5f3490192a280252cd7d04",
      "Type": "NOTE",
      "Description": "Fixed by: https://gitlab.gnome.org/GNOME/libsoup/-/commit/5a83501544a7ff180a5f3490192a280252cd7d04"
    }
  ]
}