{
  "Header": {
    "Original": "CVE-2025-2148 (A vulnerability was found in PyTorch 2.6.0+cu124. It has been declared ...)",
    "ID": "CVE-2025-2148",
    "Description": "(A vulnerability was found in PyTorch 2.6.0+cu124. It has been declared ...)"
  },
  "Annotations": [
    {
      "Original": "- pytorch \u003cunfixed\u003e (bug #1102219)",
      "Type": "package",
      "Package": "pytorch",
      "Kind": "unfixed",
      "BugNo": 1102219
    },
    {
      "Original": "[bookworm] - pytorch \u003cno-dsa\u003e (Minor issue)",
      "Type": "package",
      "Release": "bookworm",
      "Package": "pytorch",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "[bullseye] - pytorch \u003cpostponed\u003e (Minor issue)",
      "Type": "package",
      "Release": "bullseye",
      "Package": "pytorch",
      "Kind": "postponed",
      "Description": "Minor issue"
    },
    {
      "Original": "NOTE: https://github.com/pytorch/pytorch/issues/147722",
      "Type": "NOTE",
      "Description": "https://github.com/pytorch/pytorch/issues/147722"
    }
  ]
}